// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: commonfate/access/v1alpha1/identity.proto

package accessv1alpha1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on GetCallerIdentityRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetCallerIdentityRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetCallerIdentityRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetCallerIdentityRequestMultiError, or nil if none found.
func (m *GetCallerIdentityRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetCallerIdentityRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return GetCallerIdentityRequestMultiError(errors)
	}

	return nil
}

// GetCallerIdentityRequestMultiError is an error wrapping multiple validation
// errors returned by GetCallerIdentityRequest.ValidateAll() if the designated
// constraints aren't met.
type GetCallerIdentityRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetCallerIdentityRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetCallerIdentityRequestMultiError) AllErrors() []error { return m }

// GetCallerIdentityRequestValidationError is the validation error returned by
// GetCallerIdentityRequest.Validate if the designated constraints aren't met.
type GetCallerIdentityRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetCallerIdentityRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetCallerIdentityRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetCallerIdentityRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetCallerIdentityRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetCallerIdentityRequestValidationError) ErrorName() string {
	return "GetCallerIdentityRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetCallerIdentityRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetCallerIdentityRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetCallerIdentityRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetCallerIdentityRequestValidationError{}

// Validate checks the field values on GetCallerIdentityResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetCallerIdentityResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetCallerIdentityResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetCallerIdentityResponseMultiError, or nil if none found.
func (m *GetCallerIdentityResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetCallerIdentityResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetChain() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GetCallerIdentityResponseValidationError{
						field:  fmt.Sprintf("Chain[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GetCallerIdentityResponseValidationError{
						field:  fmt.Sprintf("Chain[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GetCallerIdentityResponseValidationError{
					field:  fmt.Sprintf("Chain[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if all {
		switch v := interface{}(m.GetPrincipal()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetCallerIdentityResponseValidationError{
					field:  "Principal",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetCallerIdentityResponseValidationError{
					field:  "Principal",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetPrincipal()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetCallerIdentityResponseValidationError{
				field:  "Principal",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetCallerIdentityResponseMultiError(errors)
	}

	return nil
}

// GetCallerIdentityResponseMultiError is an error wrapping multiple validation
// errors returned by GetCallerIdentityResponse.ValidateAll() if the
// designated constraints aren't met.
type GetCallerIdentityResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetCallerIdentityResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetCallerIdentityResponseMultiError) AllErrors() []error { return m }

// GetCallerIdentityResponseValidationError is the validation error returned by
// GetCallerIdentityResponse.Validate if the designated constraints aren't met.
type GetCallerIdentityResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetCallerIdentityResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetCallerIdentityResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetCallerIdentityResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetCallerIdentityResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetCallerIdentityResponseValidationError) ErrorName() string {
	return "GetCallerIdentityResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetCallerIdentityResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetCallerIdentityResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetCallerIdentityResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetCallerIdentityResponseValidationError{}

// Validate checks the field values on IdentityLink with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *IdentityLink) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on IdentityLink with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in IdentityLinkMultiError, or
// nil if none found.
func (m *IdentityLink) ValidateAll() error {
	return m.validate(true)
}

func (m *IdentityLink) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetId()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, IdentityLinkValidationError{
					field:  "Id",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, IdentityLinkValidationError{
					field:  "Id",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetId()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return IdentityLinkValidationError{
				field:  "Id",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for Label

	if len(errors) > 0 {
		return IdentityLinkMultiError(errors)
	}

	return nil
}

// IdentityLinkMultiError is an error wrapping multiple validation errors
// returned by IdentityLink.ValidateAll() if the designated constraints aren't met.
type IdentityLinkMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m IdentityLinkMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m IdentityLinkMultiError) AllErrors() []error { return m }

// IdentityLinkValidationError is the validation error returned by
// IdentityLink.Validate if the designated constraints aren't met.
type IdentityLinkValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e IdentityLinkValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e IdentityLinkValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e IdentityLinkValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e IdentityLinkValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e IdentityLinkValidationError) ErrorName() string { return "IdentityLinkValidationError" }

// Error satisfies the builtin error interface
func (e IdentityLinkValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sIdentityLink.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = IdentityLinkValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = IdentityLinkValidationError{}
