// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: commonfate/control/integration/v1alpha1/entra.proto

package integrationv1alpha1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on Entra with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Entra) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Entra with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in EntraMultiError, or nil if none found.
func (m *Entra) ValidateAll() error {
	return m.validate(true)
}

func (m *Entra) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for TenantId

	// no validation rules for ClientId

	// no validation rules for ClientSecretSecretPath

	if len(errors) > 0 {
		return EntraMultiError(errors)
	}

	return nil
}

// EntraMultiError is an error wrapping multiple validation errors returned by
// Entra.ValidateAll() if the designated constraints aren't met.
type EntraMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m EntraMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m EntraMultiError) AllErrors() []error { return m }

// EntraValidationError is the validation error returned by Entra.Validate if
// the designated constraints aren't met.
type EntraValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e EntraValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e EntraValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e EntraValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e EntraValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e EntraValidationError) ErrorName() string { return "EntraValidationError" }

// Error satisfies the builtin error interface
func (e EntraValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sEntra.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = EntraValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = EntraValidationError{}
