// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: commonfate/control/integration/v1alpha1/gcp.proto

package integrationv1alpha1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on GCP with the rules defined in the proto
// definition for this message. If any rules are violated, the first error
// encountered is returned, or nil if there are no violations.
func (m *GCP) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GCP with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in GCPMultiError, or nil if none found.
func (m *GCP) ValidateAll() error {
	return m.validate(true)
}

func (m *GCP) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ReaderWorkloadIdentityConfig

	// no validation rules for ReaderServiceAccountCredentialsSecretPath

	// no validation rules for OrganizationId

	// no validation rules for GoogleWorkspaceCustomerId

	if len(errors) > 0 {
		return GCPMultiError(errors)
	}

	return nil
}

// GCPMultiError is an error wrapping multiple validation errors returned by
// GCP.ValidateAll() if the designated constraints aren't met.
type GCPMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GCPMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GCPMultiError) AllErrors() []error { return m }

// GCPValidationError is the validation error returned by GCP.Validate if the
// designated constraints aren't met.
type GCPValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GCPValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GCPValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GCPValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GCPValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GCPValidationError) ErrorName() string { return "GCPValidationError" }

// Error satisfies the builtin error interface
func (e GCPValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGCP.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GCPValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GCPValidationError{}
